### ISSUE TITLE
Article titles are truncated at the first colon

### ISSUE THREAD

**Issue by logological** [khoulihan/pelican-gemini#1]
With this plugin enabled, article titles get truncated at the first colon.  For example, if you have an article with the metadata `Title: Foo: bar` and run it through a template that emits `{{ article.title }}`, all that gets printed is "Foo", not "Foo: bar".

**Comment by khoulihan** [comment]
Thanks for the report, I see the problem alright

**Comment by khoulihan** [comment]
Should be fixed in #7017bea
